sudo: required
services:
  - docker
before_install:
  - docker build -t suwi/devops-for-frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true suwi/devops-for-frontend npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "devops-for-frontend"
  env: "DevopsForFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-153157716099"
  bucket_path: "devops-for-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
